class Config:
    MAX_STEPS_DEFAULT = 40
    CONFIRM_ID_PREFIX = "cfm"
    CONFIRM_ID_LENGTH = 8
    MAX_CONFIRM_COUNT = 1
    CONFIRM_TIMEOUT_MS = 5000
    PRE_SEND_REVERT_WINDOW_SEC = 10.0
    POST_SEND_PATROL_THRESHOLD = 2
    WRONG_CHAT_INPUT_THRESHOLD = 2
    AWAITING_CONFIRM_TIMEOUT_SEC = 30
